**Load Library**

In [1]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
import numpy as np
import pandas as pd
from pandas import read_csv


**Load Data**

In [3]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


In [18]:
data = read_csv("/content/drive/My Drive/Colab Notebooks/Dataset AI/Klasifikasi Hoax/data.csv")
print(data.head())

  Berita  Like  Provokasi  Komentar  Emosi  Hoax
0  B0001    29         66        52     70     1
1  B0002    27         23        74     52     1
2  B0003    19         43        54     33     0
3  B0004    21         90        90     85     1
4  B0005    27         56        49     53     0


In [19]:
# creating instance of labelencoder
labelencoder = LabelEncoder()
data['Like'] = labelencoder.fit_transform(data['Like'])
data['Provokasi'] = labelencoder.fit_transform(data['Provokasi'])
data['Komentar'] = labelencoder.fit_transform(data['Komentar'])
data['Emosi'] = labelencoder.fit_transform(data['Emosi'])


In [20]:
X = data[['Like','Provokasi','Komentar','Emosi']]
y = data.Hoax


**Split Data into Training and Testing Data**

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

**Data Preprocessing**

ANN sensitif terhadap penskalaan fitur, sehingga sangat disarankan untuk menskala data yang kita miliki. Ada banyak metode berbeda untuk normalisasi data, kita akan menggunakan StandardScaler bawaan untuk standardisasi.

In [22]:
scaler = StandardScaler()
# Fit only to the training data
scaler.fit(X_train)

StandardScaler()

In [23]:
# Now apply the transformations to the data:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Training Model**

Ada banyak parameter yang dapat pilih untuk didefinisikan dan dikustomisasi dalam pemodelan ANN. Parameter yang diatur di sini adalah jumlah hidden layer dan jumlah neuron di setiap layernya. Sedangkan parameter lainnya menggunakan nilai default. Silakan mengubah parameter dan melihat pengaruhnya terhadap model pelatihan.

In [24]:
mlp = MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

Setelah model dibuat, data pelatihan di-fit-kan dengan model.

In [25]:
mlp.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  ConvergenceWarning,


MLPClassifier(hidden_layer_sizes=(30, 30, 30))

**Prediksi dan Evaluasi Model**

Dengan model yang sudah dilatih, dilakukan prediksi label dari data uji.

In [26]:
predictions = mlp.predict(X_test)
print(X_test)
print(predictions)

[[ 0.94794738 -0.13165015  1.3678172   0.39518755]
 [ 0.32085981  1.87778889  0.82475424  0.26590046]
 [-0.30622777  1.44719481  1.16416859  1.62341496]
 ...
 [ 0.07002478 -0.41871287 -0.39713742  0.07196982]
 [ 0.82252987  1.87778889 -0.19348881  1.36484077]
 [ 0.44627732 -1.0406821   0.21380841 -0.63910921]]
[1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 0 1 0 0 1 0 0 1 1 0 1
 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0
 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1
 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 0
 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 1
 1 1 1 0 1 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 1 1 0 1 1 0 1 0 1
 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 0 0 1
 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 0
 1 1 1 0 0 1 0 1 0 1 1 1 1 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 1 1 0 0 1 0 1 0
 1 1 0 0 1 1 

Untuk melihat performansi dari model, maka dilakukan evaluasi terhadap hasil prediksi, menggunakan confusion matrix, precision,recall, dan f-measure.

In [27]:
print(confusion_matrix(y_test,predictions))

[[363 174]
 [163 300]]


In [28]:
print(classification_report(y_test,predictions))
print("akurasi:",metrics.accuracy_score(y_test,predictions))

              precision    recall  f1-score   support

           0       0.69      0.68      0.68       537
           1       0.63      0.65      0.64       463

    accuracy                           0.66      1000
   macro avg       0.66      0.66      0.66      1000
weighted avg       0.66      0.66      0.66      1000

akurasi: 0.663


PREDIKSI DATA BARU

In [ ]:
testing = read_csv("/content/drive/My Drive/Colab Notebooks/Dataset AI/Klasifikasi Hoax/testing.csv")
print(testing.head())


testing['Like'] = labelencoder.fit_transform(testing['Like'])
testing['Provokasi'] = labelencoder.fit_transform(testing['Provokasi'])
testing['Komentar'] = labelencoder.fit_transform(testing['Komentar'])
testing['Emosi'] = labelencoder.fit_transform(testing['Emosi'])

X_test = testing[['Like','Provokasi','Komentar','Emosi']]
y_predict = mlp.predict(X_test)
print("\nHasil Prediksi\n")
print(y_predict)

  Berita  Like  Provokasi  Komentar  Emosi Hoax
0  B4001    14         55        68     45    ?
1  B4002    18         76        72     74    ?
2  B4003    36         68        68     69    ?
3  B4004    18         43        45     56    ?
4  B4005    18         62        71     45    ?

Hasil Prediksi

[0 0 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0
 0 1 1 0 0 1 1 1 0 1 1 1 0 1 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 1 1 0 0 1 1 1
 0 1 1 0 1 1 0 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0
 1 1 0 1 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0
 1 0 1 1 0 0 1 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 0 0 1 1 1 0 1 1
 0 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1
 1 1 1 0 1 1 0 1 0 0 1 1 1 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0
 1 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 1 1 1 0 1
 0 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 0 1
 1 0 1 1 1 0 1 1 0 0

In [ ]:
#prediksi data baru dari variabel

x_new = [[0,1,0,1]]
y_predict = mlp.predict(x_new)

print (y_predict)

[1]
